### ISSUE TITLE
Multiple adapters in cluster?

### ISSUE THREAD

**Issue by zroubalik** [kubernetes-sigs/custom-metrics-apiserver#59]
Is there a way how to deploy multiple adapters in a cluster? Eg. there's already deployed custom metrics server Foo and I need to deploy my own implementation Bar which provides different set of metrics.

If I understand it correctly, to be able to provide custome/external metrics API, the adapter needs to deploy cluster wide `APIService` with a specific name. Deploying second adapter in the cluster will results in reconfiguring the original `APIService` object.

```
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: custom-metrics-apiserver
    namespace: custom-metrics
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```
